[mgr]
cwd = { fg = "lightblue" }
find_keyword = { fg = "lightblue", bold = true }
find_position = { fg = "gray", bold = true }
symlink_target = { fg = "gray", italic = true }
marker_copied = { fg = "lightblue", bg = "lightblue" }
marker_cut = { fg = "lightred", bg = "lightred" }
marker_marked = { fg = "gray", bg = "gray" }
marker_selected = { fg = "lightblue", bg = "lightblue" }
count_copied = { fg = "black", bg = "lightblue" }
count_cut = { fg = "black", bg = "lightred" }
count_selected = { fg = "black", bg = "lightblue" }
border_style = { fg = "darkgray" }

[tabs]
active = { fg = "lightblue", bg = "darkgray", bold = true }
inactive = { fg = "gray", bg = "black" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "black", bg = "lightblue", bold = true }
normal_alt = { fg = "lightblue", bg = "darkgray" }
select_main = { fg = "black", bg = "gray", bold = true }
select_alt = { fg = "gray", bg = "darkgray" }
unset_main = { fg = "black", bg = "lightred", bold = true }
unset_alt = { fg = "lightred", bg = "darkgray" }

[indicator]
parent = { fg = "gray", bg = "black" }
current = { fg = "lightblue", bg = "darkgray" }
preview = { fg = "lightblue" }

[status]
overall = { fg = "gray", bg = "black" }
perm_sep = { fg = "darkgray" }
perm_type = { fg = "lightblue" }
perm_read = { fg = "gray" }
perm_write = { fg = "lightred" }
perm_exec = { fg = "lightblue" }
progress_normal = { fg = "lightblue", bg = "darkgray" }
progress_error = { fg = "lightred", bg = "darkgray" }

[which]
mask = { bg = "black" }
cand = { fg = "lightblue" }
rest = { fg = "gray" }
desc = { fg = "gray" }
separator_style = { fg = "darkgray" }

[confirm]
border = { fg = "lightblue" }
title = { fg = "lightblue" }
btn_yes = { fg = "black", bg = "lightblue" }
btn_no = { fg = "gray", bg = "darkgray" }

[spot]
border = { fg = "lightblue" }
title = { fg = "lightblue" }
tbl_col = { fg = "lightblue" }
tbl_cell = { fg = "gray", bg = "darkgray" }

[notify]
title_info = { fg = "lightblue" }
title_warn = { fg = "gray" }
title_error = { fg = "lightred" }

[pick]
border = { fg = "lightblue" }
active = { fg = "lightblue", bold = true }

[input]
border = { fg = "lightblue" }
selected = { fg = "black", bg = "darkgray" }

[cmp]
border = { fg = "lightblue" }
active = { fg = "gray", bg = "darkgray" }

[tasks]
border = { fg = "lightblue" }
hovered = { fg = "lightblue", bold = true }

[help]
on = { fg = "lightblue" }
run = { fg = "gray" }
desc = { fg = "gray" }
hovered = { fg = "gray", bg = "darkgray", bold = true }
footer = { fg = "gray", bg = "black" }

[filetype]
rules = [
  { mime = "image/*", fg = "gray" },
  { mime = "{audio,video}/*", fg = "gray" },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "gray" },
  { mime = "application/{pdf,doc,rtf}", fg = "gray" },
  { mime = "vfs/{absent,stale}", fg = "gray" },
  { url = "*", is = "orphan", fg = "lightred" },
  { url = "*", is = "exec", fg = "gray" },
  { url = "*", is = "dummy", fg = "lightred" },
  { url = "*/", is = "dummy", fg = "lightred" },
  { url = "*/", fg = "gray" },
  { url = "*", fg = "gray" },
]

[icon]
files = []
exts = []
dirs = [
  { name = ".config", text = "", fg = "lightblue" },
  { name = ".git", text = "", fg = "lightblue" },
  { name = ".github", text = "", fg = "lightblue" },
  { name = ".local", text = "", fg = "lightblue" },
  { name = ".ssh", text = "󰣀", fg = "lightblue" },
  { name = "Desktop", text = "", fg = "lightblue" },
  { name = "Documents", text = "", fg = "lightblue" },
  { name = "Downloads", text = "", fg = "lightblue" },
  { name = "Music", text = "", fg = "lightblue" },
  { name = "Pictures", text = "", fg = "lightblue" },
  { name = "Public", text = "", fg = "lightblue" },
  { name = "Videos", text = "", fg = "lightblue" },
]
conds = [
  { if = "orphan", text = "", fg = "lightred" },
  { if = "link", text = "", fg = "lightblue" },
  { if = "dir & hovered", text = "", fg = "lightblue" },
  { if = "dir", text = "", fg = "lightblue" },
  { if = "exec", text = "", fg = "lightblue" },
  { if = "!dir", text = "", fg = "lightblue" },
]
