name = "Matugen"
background = "{{colors.background.default.hex}}"
surface = "{{colors.surface.default.hex}}"
text = "{{colors.on_background.default.hex}}"
accent = "{{colors.primary.default.hex}}"
danger = "{{colors.error.default.hex}}"
muted = "{{colors.surface_variant.default.hex}}"
highlight = "{{colors.primary_container.default.hex}}"
border = "{{colors.outline.default.hex}}"
dim_text = "{{colors.on_surface_variant.default.hex}}"
syntax_keyword = "{{colors.secondary.default.hex}}"
syntax_string = "{{colors.tertiary.default.hex}}"
syntax_constant = "{{colors.on_surface.default.hex}}"
syntax_type = "{{colors.secondary_container.default.hex}}"
syntax_preprocessor = "{{colors.tertiary_container.default.hex}}"
