###############################################################################
# Environment Initialization
#
# Initializes third-party tools and environment variables.
###############################################################################

###############################################################################
# Homebrew
###############################################################################

# Initialize Homebrew environment if installed
if [[ -x "/home/linuxbrew/.linuxbrew/bin/brew" ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

###############################################################################
# Node Version Manager (NVM)
###############################################################################

# Set NVM environment variables
export NVM_DIR="${HOME}/.nvm"
export NVM_HOMEBREW="/home/linuxbrew/.linuxbrew/opt/nvm"

# Load NVM if available
if [[ -s "${NVM_HOMEBREW}/nvm.sh" ]]; then
  # shellcheck source=/dev/null
  . "${NVM_HOMEBREW}/nvm.sh"
fi

###############################################################################
# Zoxide
###############################################################################

# Initialize zoxide
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init bash)"
fi

###############################################################################
# Starship
###############################################################################
#eval "$(starship init bash)"

###############################################################################
# FZF
###############################################################################

# Read the current DMS Material colors generated by Matugen.
DMS_COLORS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/dank-colors.css"

__dms_color() {
  local color_name="$1"
  local fallback="$2"
  local color

  color="$(
    sed -n \
      "s/^@define-color ${color_name} #\\([[:xdigit:]]\\{6\\}\\);/\\1/p" \
      "$DMS_COLORS_FILE" 2>/dev/null |
      head -n 1
  )"

  printf '%s' "${color:-$fallback}"
}

FZF_FOREGROUND="$(__dms_color window_fg_color dfe3e7)"
FZF_PRIMARY="$(__dms_color accent_bg_color 90cef4)"
FZF_ON_PRIMARY="$(__dms_color accent_fg_color 00344a)"

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --border=none \
  --color=bg+:#${FZF_PRIMARY} \
  --color=bg:-1 \
  --color=border:#${FZF_PRIMARY} \
  --color=fg:#${FZF_FOREGROUND} \
  --color=fg+:#${FZF_ON_PRIMARY} \
  --color=gutter:-1 \
  --color=header:#${FZF_FOREGROUND} \
  --color=hl+:#${FZF_ON_PRIMARY} \
  --color=hl:#${FZF_PRIMARY} \
  --color=info:#${FZF_PRIMARY} \
  --color=marker:#${FZF_PRIMARY} \
  --color=pointer:#${FZF_PRIMARY} \
  --color=preview-bg:-1 \
  --color=preview-border:#${FZF_PRIMARY} \
  --color=preview-fg:#${FZF_FOREGROUND} \
  --color=prompt:#${FZF_PRIMARY} \
  --color=query:#${FZF_FOREGROUND}:regular \
  --color=scrollbar:#${FZF_PRIMARY} \
  --color=separator:#${FZF_PRIMARY} \
  --color=spinner:#${FZF_PRIMARY} \
"
