[general]
import = ["~/.config/alacritty/dank-theme.toml"]

[window]
 opacity = 0.8
decorations = 'none'
# blur = true
# padding = {x = 6, y = 6}
# Default colors

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
offset = {x = 0, y = 1}

size = 11.0

[colors.primary]
background = '#282c34'
