unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

# Easier split keys
bind s split-window -h
bind v split-window -v

# Copy-mode on Ctrl-c
bind C-c copy-mode

set -g base-index 1
set -g pane-base-index 1

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Mouse support
set -g mouse on