[config]

[templates.starship]
input_path = "~/.dotfiles/dots/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship/starship.toml"

[templates.strata]
input_path = "~/.dotfiles/dots/.config/matugen/templates/strata.toml"
output_path = "~/.config/strata/themes/matugen.toml"

[templates.niri]
input_path = "~/.dotfiles/dots/.config/matugen/templates/niri.kdl"
output_path = "~/.config/niri/colors.kdl"

[templates.rofi]
input_path = "~/.dotfiles/dots/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.wofi]
input_path = "~/.dotfiles/dots/.config/matugen/templates/wofi.css"
output_path = "~/.config/wofi/style.css"

[templates.spotifyplayer]
input_path = "~/.dotfiles/dots/.config/matugen/templates/spotify_player.toml"
output_path = "~/.config/spotify-player/theme.toml"
