onboarding = false

[theme]
name= "terminal"

[ui]
sidebar_start_collapsed = false
sidebar_collapsed_mode = "compact"

show_agent_labels_on_pane_borders = true

agent_panel_sort = "priority"
[keys]
prefix = "ctrl+a"
goto = ["prefix+g", "alt+shift+p"]
toggle_sidebar = ["prefix+b", "alt+shift+b"]
new_workspace = ["prefix+shift+n", "alt+shift+n"]

new_worktree = ["prefix+shift+g", "alt+shift+g"]
open_worktree = ["prefix+shift+o", "alt+shift+o"]
remove_worktree = "prefix+alt+d"

split_vertical = ["prefix+v", "ctrl+shift+right", "alt+shift+h"]
split_horizontal = ["prefix+minus", "ctrl+shift+down", "alt+shift+v"]
close_pane = ["prefix+x", "ctrl+shift+left"]

new_tab = ["prefix+c", "alt+shift+c"]
rename_tab = ["prefix+,", "alt+shift+t"]
previous_tab = ["prefix+p", "alt+shift+u"]
next_tab = ["prefix+n", "alt+shift+i"]
rename_workspace = "prefix+$"
rename_pane = "prefix+."

focus_pane_left = ["prefix+h", "alt+left"]
focus_pane_right = ["prefix+l", "alt+right"]
focus_pane_up = ["prefix+k", "alt+up"]
focus_pane_down = ["prefix+j", "alt+down"]

resize_mode = "prefix+r"
resize_pane_left = "alt+shift+left"
resize_pane_right = "alt+shift+right"
resize_pane_up = "alt+shift+up"
resize_pane_down = "alt+shift+down"
zoom = ["prefix+z", "alt+shift+z"]

[remote]
manage_ssh_config = false

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "40%"
height = "50%"
